### ISSUE TITLE
count command behaviour for multi-byte symbols

### ISSUE THREAD

**Issue by david-fong** [lcheng1/decabyt.es#23]
[Here's an interesting read](https://mathiasbynens.be/notes/javascript-unicode#counting-symbols) that you may be interested in incorporating into your count command (depending on what you're going for).

Cheers!

**Comment by lcfyi** [comment]
That's actually super interesting, I haven't come across this yet but it's definitely an edge-case I'd like to avoid. Thanks for pointing it out!
